sudo: false
language: node_js
dist: trusty
node_js:
  - '7'
addons:
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
cache:
  directories:
  - node_modules
after_script:
  - npm run coveralls
after_success:
  - cat ./coverage/report-lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
cache:
  directories:
    - node_modules
